DROP TABLE IF EXISTS products_pictures;
DROP TABLE IF EXISTS posters;
DROP TABLE IF EXISTS packaging;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS providers;
DROP TABLE IF EXISTS mercado_libre_categories;
DROP TABLE IF EXISTS configuration;